### ISSUE TITLE
Add wporg submenu

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#1]
**Menu Items**
- Submit a site

**Acceptance criteria**
- Clicking on "Showcase" should go to showcase home
- If we are viewing, a tag/category/search archive it should have the appropriate word added 
  - Ie: "Showcase &middot; Results"
- The subnav should stretch full screen( [Ref](https://github.com/WordPress/wporg-main-2022/issues/129#issuecomment-1262750330) )

I'm not sure how to do this without a custom block. I looked into doing something like [local-navigation](https://github.com/WordPress/wporg-news-2021/blob/trunk/source/wp-content/themes/wporg-news-2021/block-template-parts/local-navigation.html) and maybe use [get_the_archive_title](https://developer.wordpress.org/reference/hooks/get_the_archive_title/) but it's also used on the search page which doesn't call that function. I don't see a hook for modifying the search title.

# Designs
We have a few versions:
<img width="887" alt="Screen Shot 2022-10-31 at 10 28 41 AM" src="https://user-images.githubusercontent.com/1657336/198913516-04bf7133-db5a-4bb3-9b8b-877cd49040f6.png">
<img width="889" alt="Screen Shot 2022-10-31 at 10 28 31 AM" src="https://user-images.githubusercontent.com/1657336/198913520-f2f16fac-3215-4e4c-8081-62cc2a0befdd.png">
<img width="892" alt="Screen Shot 2022-10-31 at 10 28 20 AM" src="https://user-images.githubusercontent.com/1657336/198913522-2ce935d0-ab70-4d03-837c-df605bb2eae8.png">
<img width="710" alt="Screen Shot 2022-11-14 at 2 11 17 PM" src="https://user-images.githubusercontent.com/1657336/201580615-04e33b9f-78ab-479a-bc4e-8bb7e4c7a028.png">

**Comment by ryelle** [comment]
This seems to be a consistent design element (see https://github.com/WordPress/wporg-main-2022/issues/129), so it should be added to the parent theme.

**Comment by StevenDufresne** [comment]
The color scheme has changed.
