### ISSUE TITLE
Layout: Submit Site Assets

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#10]
We have decided to hold off on launching this page. See #41 for context.

<hr>

This page contains assets that showcase site owners can download.

Current page: https://wordpress.org/showcase/submit-a-wordpress-site/graphics/.

# Designs

![image](https://user-images.githubusercontent.com/1657336/196576726-7c7e3865-d738-41aa-b336-caa4536c00a0.png)

### Mobile
Link: https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase-Pages?node-id=884%3A12798

<img src="https://user-images.githubusercontent.com/1657336/198908617-aeb65f41-7b7b-458b-91e5-1142ac12202f.png" width="300px">

**Comment by ryelle** [comment]
Closing in favor of #131
