### ISSUE TITLE
If there are no related posts, provide some.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#105]
Some posts are returning no related posts. 

We have 2 options:
- Improve the content, associate more terms
- Provide some programmatically.

**Programmatically**
We can use the `filter_hits` filter and return posts from the "featured" category.

Ref: https://developer.jetpack.com/hooks/jetpack_relatedposts_filter_hits/

**Comment by ryelle** [comment]
Closing in favor of #140, which will use the programmatic approach (though hopefully the content will be better, too)
