### ISSUE TITLE
Remove hover state for the hero thumbnail

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-showcase-2022#107]
This [issue](https://github.com/WordPress/wporg-showcase-2022/issues/98) introduced the hover states for the thumbnails, but the hero image shouldn't be highlighted. Sorry if this wasn't clear from the issue description.

**Comment by StevenDufresne** [comment]
Done: [16ed824](https://github.com/WordPress/wporg-showcase-2022/commit/16ed8244b6822866f5e07088adf45b6f25409295).
