### ISSUE TITLE
Tweaks to the Submission form

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-showcase-2022#108]
I noticed some differences between the design of the [submission form](https://wordpress.org/showcase/submit-a-wordpress-site) and [the design] (https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase-Pages?node-id=1771%3A24626&t=XFTpvJPXd0SaMVpl-4) that would be nice to address:

- The required label should be the same font size as the title label, but in a darker shade of grey ("WP.org Charcoal 4" or #656A71)
- The input fields and the textareas should have rounded corners (2px) and lighter border color ("WP.org Charcoal 4" or #656A71)
- On a desktop, the input fields should be shorter to avoid the blocky look of the current form.

![image](https://user-images.githubusercontent.com/4933/207629806-e8dcc85b-d53b-46f9-a8e2-07b7a2bcd663.png)

cc: @beafialho @jasmussen

**Comment by StevenDufresne** [comment]
Nothing that the borders were already to `charcoal-4` and that style was being applied properly.

https://github.com/WordPress/wporg-showcase-2022/blob/main/source/wp-content/themes/wporg-showcase-2022/src/style/style.scss#L128

**Comment by StevenDufresne** [comment]
> The required label should be the same font size as the title label, but in a darker shade of grey ("WP.org Charcoal 4" or #656A71)

I assume you mean `lighter shade of grey`, since charcoal-4 is considered lighter.

<hr>

I've made the request updates in https://github.com/WordPress/wporg-showcase-2022/commit/58469ff30194f3198a7cff0fae219bc61736bf4e. Please reopen if we need any more changes. 👍
