### ISSUE TITLE
Replace Featuring header with tagline

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-showcase-2022#113]
Instead of showing "Featuring: Title of the site" over the main image, let's show the tagline: "Best-in-class Sites on WordPress"

![image](https://user-images.githubusercontent.com/4933/207834842-f821cd3a-2f20-480c-ba56-eaab66a6460e.png)

**Comment by javierarce** [comment]
I'd prefer to use the proposed title instead of "The Best WordPress Sites in the World" (which it's a bit longer and would require reducing the size of the main title), but it's not a hard opinion.

cc: @jasmussen @pablohoney

**Comment by StevenDufresne** [comment]
@javierarce Are we waiting for feedback on this one?

cc: @jasmussen

**Comment by javierarce** [comment]
Since we had agreed to replace the site's title with the tagline, I think we can move forward with the change and open a new issue in case we want to adjust the copy later.
