### ISSUE TITLE
Reduce the font size of site's titles in mobile

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-showcase-2022#114]
In small viewports, the site titles should be set in smaller font size. They are currently 20px, but they should appear in 16px

Before/After image: 
![image](https://user-images.githubusercontent.com/4933/207842274-5568244a-9ccb-47db-bc53-d5f57120084d.png)

**Comment by ryelle** [comment]
@javierarce This is using the "large" font size, which according to the design library has no change on mobile — is this a change we should make in the parent theme for all sites using "large" text, or is this a change specific to showcase/these titles?

**Comment by javierarce** [comment]
Right now this is just a special case for Showcase.

**Comment by StevenDufresne** [comment]
@ryelle Do you know if there's a way to do this without a custom class somewhere in/around the post-template & CSS? 

I tried adding a new font size to the showcase theme.json `fontSizes` array, hoping to use `clamp`, but it wiped out all the parent props.

**Comment by StevenDufresne** [comment]
Noting your open [Gutenberg Issue](https://github.com/WordPress/gutenberg/issues/40557). :)

**Comment by StevenDufresne** [comment]
@javierarce 

Also noting that the designs only have the font size reduced for grid items on the homepage. The search results, which include the extra except, don't have any change in their heading size on mobile.
https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase-Pages?node-id=1884%3A23648&t=nSCSYoThhxlR9wLl-0 

I'll update the search results grid as well for consistency. If that is incorrect and only the featured section should get this treatment, please let me know.
