### ISSUE TITLE
Add placeholder for site's images

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-showcase-2022#115]
We should add placeholders states for the thumbnails in case the user's connection is slow.

I propose to use Charcoal 3 (#40464D) for the large images and Light Gray (#D9D9D9) for the smaller thumbnails.

![image](https://user-images.githubusercontent.com/4933/207844007-64fa32d7-4ea9-437b-89f4-eae975044897.png)

**Comment by StevenDufresne** [comment]
Yep, that makes sense. 

Added:
https://github.com/WordPress/wporg-showcase-2022/commit/b237bdee7108044d6deed581d39f7600ee644b3b
https://github.com/WordPress/wporg-showcase-2022/commit/19a31df6a2fe8a503a2b6cef9f3a2667872ca959
https://github.com/WordPress/wporg-showcase-2022/commit/85f64eb1985cce3bb39fde03ae5fc2c3b7576f2e
