### ISSUE TITLE
Add ability to navigate older sites

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-showcase-2022#117]
During the build of the new websites the existing list was cleaned up to remove websites that no longer fit the requirements for the Showcase. We should consider a way to archive sites so moving forward the archive accumulates over time.

This likely is more of a content maintenance task and may not need development work, but I wanted to add an issue here for consideration in the future.

**Comment by StevenDufresne** [comment]
I'm not certain I understand is necessary. We have an archive. Do we want a secondary archive of sites that no longer fit the requirements?

**Comment by bengreeley** [comment]
@StevenDufresne The way I interpret this request is not necessarily adding a second archive but rather changing the content maintenance policy not to remove sites when new ones are added (which I believe was the original plan). I believe the goal was to try to keep the number of sites to a minimum. This request is asking we continue adding sites to the archive.

I do still feel strongly we shouldn't add any sites that are no longer using WordPress (otherwise, why would we want to have them on the site?), so it could be many of the sites that were removed should stay removed. This issue should be one the content maintenance team should weigh in on in the future. Does that help clarify?

**Comment by StevenDufresne** [comment]
> Does that help clarify?

Yes

> This issue should be one the content maintenance team should weigh in on in the future.

Yes

My opinion is that the homepage should have more sections that lead users down categorized paths. Analytics suggests that users do like to travel down these paths. "Business" was a good example from the previous design. The archive would display sites based on publish dates and the "old" site would likely be at the bottom of the pile. The same would happen when browsing categories. They may show up as a related site _early_... But we can filter those out. Assigning these posts a category would make that easier to do.

**Comment by jasmussen** [comment]
Coming in fresh on this issue, forgive me if I'm missing context. What exists in the archive of the old version is arguably of limited value simply due to the age of the submissions. Browsing it, I recall some sites 404'ing, others being entirely redesigned. Can we archive them in the sense that they become unpublished? There doesn't seem to be a huge value in keeping them browsable.

**Comment by bengreeley** [comment]
Agreed, @jasmussen. We intentionally removed many sites that didn't make sense to feature in the directory.

The original request was `Need ability to navigate, view sites that were in the previous version of the showcase` with a further clarification of `The featured section should only have high quality sites, but would be good to have an archive that accumulates over time. Something that doesn’t need to be maintained. Could tag them separately, etc.`

To me, this seems like we already have the functionality in place to handle this, but will just need to keep sites in the Showcase instead of removing them for content maintenance.

If that makes sense to both of you as well, I can close this task since I don't think it needs any development work.
