### ISSUE TITLE
Add an additional ‘Submit a Site’ CTA closer to the top of the page.

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-showcase-2022#118]
The homepage should have an additional 'Submit a Site' CTA closer to the top of the page, likely near the 'Featured Sites' section.

**Comment by jasmussen** [comment]
Here's some work in progress for a pattern directory refresh. 

<img width="1376" alt="Screenshot 2023-01-13 at 09 58 27" src="https://user-images.githubusercontent.com/1204802/212279662-695b8923-e38d-4ab5-a607-730b30e2fcdd.png">

As you can see it shares a little DNA in terms of the top header and cover, and features a "login" item in the top right. Perhaps that same spot could work as a "Submit site" link?

**Comment by ryelle** [comment]
Submit is in the top-right nav across the redesign, so this will be added as the redesign is rolled out.

<img width="518" alt="Screenshot 2023-07-31 at 11 33 14 PM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/abaa096a-098f-45d1-b5c3-632ca5d26fd0">
