### ISSUE TITLE
Reintroduce Tags

### ISSUE THREAD

**Issue by bengreeley** [WordPress/wporg-showcase-2022#119]
Add tags and metadata back in “so we can point to a bunch of great government sites, or authors, or startups, etc. that way, when a new one comes in, we can say look at all these other awesome XYZ sites that are already using WP.”

**Comment by jasmussen** [comment]
This seems like a good spot to add metadata:

<img width="854" alt="Screenshot 2023-01-13 at 10 00 10" src="https://user-images.githubusercontent.com/1204802/212280043-58e65e29-cfc9-4536-a006-4d19968f6fe8.png">

**Comment by ryelle** [comment]
The tag, category, and flavors will be added as part of #132, closing in favor of that issue.
