### ISSUE TITLE
The old version is displayed instead of the 2022

### ISSUE THREAD

**Issue by Besyar** [WordPress/wporg-showcase-2022#124]
Why is the previous version of the showcase still displayed?
https://wordpress.org/showcase/

**Comment by Besyar** [comment]
@StevenDufresne Any comment?!

**Comment by StevenDufresne** [comment]
There was a decision made to rollback the showcase theme. 

You can read more about it in the WP.org slack channel:
https://wordpress.slack.com/archives/C02QB8GMM/p1676876490380769
