### ISSUE TITLE
Submit a Site page

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#131]
[Figma Source](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase?type=design&node-id=3291%3A68596&mode=design&t=oZhs4hIMd1ft8Tab-1)

<table role="table">
<thead>
<tr>
<th>Small</th>
<th>Medium</th>
<th>Large</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256118398-dac16638-8636-437f-8734-12aef281d36e.png"><img src="https://user-images.githubusercontent.com/111751264/256118398-dac16638-8636-437f-8734-12aef281d36e.png" alt="(Mobile) Showcase - Submit a Site" style="max-width: 100%;"></a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256117825-41059b68-09ba-4cc8-8dc8-7cec204e5882.png"><img src="https://user-images.githubusercontent.com/111751264/256117825-41059b68-09ba-4cc8-8dc8-7cec204e5882.png" alt="Showcase - Submit a Site" style="max-width: 100%;"></a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256118401-05a7f5c6-f96e-4eef-b59f-0721e9a52b17.png"><img src="https://user-images.githubusercontent.com/111751264/256118401-05a7f5c6-f96e-4eef-b59f-0721e9a52b17.png" alt="(Monitor) Showcase - Submit a Site" style="max-width: 100%;"></a></td>
</tr>
</tbody>
</table>

If the user is not logged in, the page content should not display, instead it should show a log in message:

![Showcase - Log in to Submit a Site](https://github.com/WordPress/wporg-showcase-2022/assets/111751264/43350340-e6e9-4fb3-8c66-aae8ca4356a9)

After submission, show a success page

![Showcase - Your site has been submitted](https://github.com/WordPress/wporg-showcase-2022/assets/111751264/08a5e25e-52c0-489d-809d-05f94d53da35)

**Comment by thetinyl** [comment]
### Copy edits for the "Submit a site" page

There were a few small things I noticed that might benefit from some updates. I copied the page in Figma to make the edits and then highlighted them so they might be easier to see in context. 

![Highlighted copy edits for Submit a site_Showcase](https://github.com/WordPress/wporg-showcase-2022/assets/100625704/a1e72108-7d9e-4737-b4fc-d8e6d7a0c605)

Some of these changes are grammar/syntax/spelling related, like updating "web sites" to "websites", changing an ampersand to an "and", or adding missing punctuation. Other changes relate to consistency in language and how we're applying the brand tone and voice, like "Thank you" to "Thanks"... we say "Thanks" elsewhere in the experience and it fits with the informal tone. Additional edits are more for clarity and finesse like the last question in the form read a bit oddly and needed some smoothing out.

### Copy edits for "Success" page

Based on the most recent version of this page in staging (screenshot below), I have some additional suggested edits.

<img width="1035" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/100625704/276c98f6-96ed-43d0-883d-5fb0ac06a24f">

Suggested copy changes:

- Drop the ", thanks" from the headline to read simply: "Your site has been submitted" (it doesn't flow nicely and feels a bit like a throwaway line)
- Edit the first line of body copy to read: "Thanks for your interest in the WordPress Showcase!" (based on the [brand guidelines](https://make.wordpress.org/marketing/handbook/resources/style-guide-and-brand-book/#writing-about-wordpress), we try not to use "we" if it's not directly relating to the community)
- In the last line of body copy, change "via email" to "by email" ("via" feels both technical and formal)

@ryelle Let me know if there's anything else needed here. All the other copy looked fine to me.
