### ISSUE TITLE
Single Site

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#132]
Useful links:
[Figma Source](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase?type=design&node-id=3291%3A68596&mode=design&t=oZhs4hIMd1ft8Tab-1)

[Screenshots](https://drive.google.com/drive/folders/13z0vaiGxp4Es9q1PPi5rHenX94AQrLjl?usp=drive_link)

<table role="table">
<thead>
<tr>
<th>Mobile</th>
<th>Desktop</th>
<th>Monitor</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256119207-bc9a5ce2-500a-4ed2-8b63-478339ea236c.png"><img src="https://user-images.githubusercontent.com/111751264/256119207-bc9a5ce2-500a-4ed2-8b63-478339ea236c.png" alt="(Mobile) Showcase - Single" style="max-width: 100%;"></a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256119153-7090a192-f9f2-48fc-9a32-15798000a0c9.png"><img src="https://user-images.githubusercontent.com/111751264/256119153-7090a192-f9f2-48fc-9a32-15798000a0c9.png" alt="(Desktop) Showcase - Single" style="max-width: 100%;"></a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256119235-3c4fbf0a-c385-48fc-bca7-dfce87b4351c.png"><img src="https://user-images.githubusercontent.com/111751264/256119235-3c4fbf0a-c385-48fc-bca7-dfce87b4351c.png" alt="(Monitor) Showcase - Single" style="max-width: 100%;"></a></td>
</tr>
</tbody>
</table>

Hero sites have manual selection of colors. See #138

**Comment by ryelle** [comment]
All aspects of the single site page have been completed, except for related sites which is tracked in #140. New issues can be created for any feedback or fixes.
