### ISSUE TITLE
Archive template

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#134]
See #136 for the site cards & grid, this just puts it together for the archive views.

[Figma Source](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase?type=design&node-id=3291%3A68596&mode=design&t=oZhs4hIMd1ft8Tab-1)

<table role="table">
<thead>
<tr>
<th>Mobile</th>
<th>Desktop</th>
</tr>
</thead>
<tbody>
<tr>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256120675-347cb901-9b6b-48e3-9395-a16f206fb18b.png"><img src="https://user-images.githubusercontent.com/111751264/256120675-347cb901-9b6b-48e3-9395-a16f206fb18b.png" alt="(Mobile) Showcase - View All Sites" style="max-width: 100%;"></a></td>
<td valign="top"><a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/111751264/256120673-9031f633-d980-403f-9459-99a14debcbf1.png"><img src="https://user-images.githubusercontent.com/111751264/256120673-9031f633-d980-403f-9459-99a14debcbf1.png" alt="(Desktop) Showcase - View All Sites" style="max-width: 100%;"></a></td>
</tr>
</tbody>
</table>

**Comment by ryelle** [comment]
All aspects of the archive template have been completed. New issues can be created for any feedback or fixes.
