### ISSUE TITLE
Site cards & grid

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-showcase-2022#136]
The homepage and archive pages have a grid of sites displayed. Currently this uses a Query Loop & blocks to create the site thumbnail cards. The style of these blocks needs to be updated, and the site tags should be added.

![Content grid](https://github.com/WordPress/wporg-showcase-2022/assets/541093/9240118f-57b7-4a78-86e6-c2b2304f9310)

Image hover & focus state should get a darker border on the image (will need to check accessibility on this).

<img width="1274" alt="Screenshot 2023-07-31 at 10 33 50 PM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/f83419f4-a9c1-4e88-9fea-8a87fecc3345">

**Comment by ryelle** [comment]
@WordPress/meta-design In practice, it looks like [these sites will have more tags than expected](https://wordpress.org/showcase-v2/archives/), which can cause the content to wrap on to a new line:

<img width="1270" alt="Screenshot 2023-08-03 at 1 45 02 PM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/ace8cd83-5237-471a-a56c-7fb4a5b69d98">

How should the thumbnail cards handle this?

**Comment by marko-srb** [comment]
@ryelle 

Thanks for the ping. I was considering this in one of the previous designs, but not sure where. Attached is a quick mockup.

As I am not 100% sure this is good to do for the tags, I am the same % sure we cannot house 6+ tags under one site entry and 2 tags under the other one on the right, and still have anything decent looking in the feed (archive, landing, or results) — spacings would be too off and things would become to weird... Meaning, I consider this approach a 'best solution' even if hard to consider in the code. And then all tags could be shown only under the single site page.

@WordPress/meta-design what do you think?

Thanks!

<img width="1384" alt="Screen Shot 2023-08-04 at 01 20 58" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/eb1680d6-43e0-4d43-afce-fff192af7ac6">

**Comment by fcoveram** [comment]
I think that adding `…` at the end can work.

I tried it in two breakpoints and it seems that limiting labels number to three gives enough space to keep texts in a single line.

<img width="1528" alt="Grid of site cards on desktop and mobile" src="https://github.com/WordPress/wporg-showcase-2022/assets/895819/c8c4319c-0f73-41c5-8f17-a2b5b844b3a9">
