### ISSUE TITLE
Screenshots: Avoid showing scrollbars

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-showcase-2022#142]
I'm assuning all the following screenshots are automatically taken, but since the [Chrome inspector process suggested here](https://github.com/WordPress/wporg-showcase-2022/issues/138#issuecomment-1663481689) should omit scrollbars, I'll assume the following examples are from the mShots process. These automated screenshots ([from this list](https://github.com/WordPress/wporg-showcase-2022/pull/141#issuecomment-1668311260)) all include a scrollbar:

<img width="286" alt="Screenshot 2023-08-08 at 09 40 51" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/82af9a81-a620-4ed5-804e-21e18b95b8a5">

<img width="275" alt="Screenshot 2023-08-08 at 09 40 55" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/f8dae4a8-401b-43ca-b0e8-c77f7bb59a5d">

<img width="232" alt="Screenshot 2023-08-08 at 09 40 58" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/314eb3d3-e53d-4c7a-8542-893059a8d7dc">

<img width="244" alt="Screenshot 2023-08-08 at 09 41 01" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/5ef7cdbb-d46b-4915-b9fc-860dfe417e9d">

<img width="294" alt="Screenshot 2023-08-08 at 09 41 06" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/a1f4c84d-1919-4c12-9afe-007a50dd27f2">

The screenshots should not include a scrollbar. Is it possible to add some custom HTML to the sites before snapping the screenshot, something like:

```
html, body {
overflow: hidden;
}
```

?

**Comment by jasmussen** [comment]
Ah, apologies, it was my impression that [using the process of using Chrome to grab the screenshots](https://github.com/WordPress/wporg-showcase-2022/issues/138#issuecomment-1663481689) would automatically omit any scrollbars, which is why I thought this was mShots.

**Comment by marko-srb** [comment]
Hey hey, 

I updated the list of screenshots in the same google drive, with a comments somewhere too. So we have screenshots without the right scrollbars. These are present with one day delay after the initial ones were in Google Drive. Please use that folder:


https://drive.google.com/drive/folders/1HTZxL8c_L7RlilcWztc-XZfPA6EkvOve?usp=drive_link

Thank you!

CC: @ryelle @jasmussen

**Comment by marko-srb** [comment]
> Ah, apologies, it was my impression that [using the process of using Chrome to grab the screenshots](https://github.com/WordPress/wporg-showcase-2022/issues/138#issuecomment-1663481689) would automatically omit any scrollbars, which is why I thought this was mShots.

And I think it doesn't. I think I used exact same way for taking screenshots, while it left the right scrollbar visible on many sites... Where scroll is manipulated with the scripts, it doesn't show them, while on every other place it shows the right scrollbar... I also think I saw there's a tiny hack for that, but I need to check that after I am back from AFK...

**Comment by ryelle** [comment]
The five sites already mentioned are the only ones on the showcase-v2 site, and they've all been updated already 👍🏻 

For the other screenshots, I'll just cc @jpantani since marketing will be entering that content.

To get this issue closed, is there anything else that needs to happen here? @jasmussen did you want to update the wiki page with [this info](https://github.com/WordPress/wporg-showcase-2022/issues/138#issuecomment-1663481689)? you should have access now.

**Comment by jasmussen** [comment]
We can close this one and follow up separately. I updated the wiki.
