### ISSUE TITLE
Site focus color: Refine process

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-showcase-2022#143]
From [the discussion here](https://github.com/WordPress/wporg-showcase-2022/pull/141#issuecomment-1668311260), looking at these sites:

* [Noma](https://wordpress.org/showcase-v2/noma/)
* [The Line Hotels](https://wordpress.org/showcase-v2/the-line-hotels/)
* [Caeserstone](https://wordpress.org/showcase-v2/caeserstone/)
* [Dita](https://wordpress.org/showcase-v2/dita/)
* [Tonal](https://wordpress.org/showcase-v2/tonal/)

These are all beautiful sites. The spotlight color (the bg behind the screenshots) is impressively chosen, but it is also not perfect, in some cases becoming muted or feeling unrelated to the content of the screenshots. 

First off, all these sites are lovely enough that they deserve a custom chosen color. Here are suggestions, but would appreciate input by @fcoveram when he has a chance.

Noma:

#f9f9f3

![wordpress org_showcase-v2_noma_](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/b5392994-c4c6-4de9-a060-f1e30c13ae37)

Line hotels: color is great.

Caesarstone:

#dcd4cf

![wordpress org_showcase-v2_caeserstone_](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/ac1d781b-6e83-450a-9505-c8286a63c194)

Dita:

#2b3739

![wordpress org_showcase-v2_dita_](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/581eca09-ff61-4349-8173-c43c2f4d2d7c)

Tonal:

#5e4c44

![wordpress org_showcase-v2_tonal_](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/3e1232c5-2096-4dc8-a2c2-ac1cee97c067)

The question then is: do we want to keep the automated color deduction for the remaining sites, or do we want to only keep curated colors like the above and then fall back to light gray for any site that doesn't have a manually entered color? I lean towards the latter, but not strongly, and happy to try this a bit more.

**Comment by fcoveram** [comment]
Regarding hex colors:
* **Noma** looks slightly grey compared to the background. I'd add more yellow to the tone.
* **Dita** looks not dark enough to outline the device border. The tone is correct but more darkness is needed.

Regarding color configuration, I'm afraid that curated colors might put a heavy burden on the curator's shoulders. I prefer the deduction color able to be replaced by a customized one.

**Comment by jasmussen** [comment]
Right, I think it's mainly a decision point: do we fall back to light gray unless curated? Or do we fall back to the deducted color unless curated. I leaned softly towards falling back to gray, because picking the right shade feels important. But I also know that Francisco has spent more time with this, so I would lean to his decision. So I'm happy to keep that as a baseline, we can always revisit.
