### ISSUE TITLE
Tags query filter not working

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-showcase-2022#150]
The URL for filtering sites by tag does not work on WordPress.org, despite working locally.

For example: `https://wordpress.org/showcase-v2/archives/?tag%5B%5D=design&tag%5B%5D=e-commerce`

This seems to be a wp.org-wide issue, since the same result appears on `https://wordpress.org/news/?tag[]=development`

Category and Flavor filters still work: https://wordpress.org/showcase-v2/archives/?cat%5B%5D=343&flavor%5B%5D=wordpress-org

**Comment by pkevan** [comment]
Interesting - you can also query tags via `?tag=[tag1],[tag2]`, which results in the correct results.

e.g. https://wordpress.org/showcase-v2/archives/?tag=bars,dining

**Comment by ryelle** [comment]
The example URL is built by a form of checkboxes, which results in the `tag` array from native HTML behavior. I'd rather not add any special handling to create a different URL when arrays are valid tag values. In any case, thanks to @tellyworth's sleuthing, it was [an easy fix](https://meta.trac.wordpress.org/changeset/12884) 🙂
