### ISSUE TITLE
Consider linking site title in Hero heading

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#155]
When I land on the homepage, we show our "best/featured" image. It isn't apparent to me how I can visit that single page site. I can do so by clicking on the image, but other than changing the cursor on mouseover, that interaction is mostly hidden. 

Should we link site title in the left details bar?

# Screenshot
<img width="1560" alt="Screenshot 2023-09-18 at 9 08 51 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/1657336/bf14dd54-b25f-4e3b-ba20-16d071146a17">

**Comment by StevenDufresne** [comment]
cc @WordPress/meta-design

**Comment by jasmussen** [comment]
Yep, good call. The title can be underlined on hover and link to the permalink, same as the thumbnail does.

**Comment by ryelle** [comment]
Done in https://github.com/WordPress/wporg-showcase-2022/commit/32e8a99c8f2ff98a8e4465ae1aab806ab6043875 (mixed up the issues in the commit)
