### ISSUE TITLE
Images seem larger than they need to be.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#156]
The image file sizes appear too large and result in a heavy page load burden (which affects performances scores).

If this is solely the result of missing screenshots, feel free to close this.

We should: 
- Make sure images are compressed before upload (or on upload)?
- Provide more appropriately sized images

## Screenshots
<img width="750" alt="Screenshot 2023-09-18 at 9 29 03 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/1657336/873f5083-2a17-4a3b-8e0e-c64f194db8b2">
<img width="717" alt="Screenshot 2023-09-18 at 9 32 23 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/1657336/4fca5f4c-435a-42d6-9f12-9ccd99ef8a1c">

**Comment by ryelle** [comment]
This is the uploaded images, and they're already being served via Jetpack CDN in webp format.

The screenshot block has no context for whether it's showing an image in the grid (where the image could be anywhere from 340 × 190 to 740 × 415), or the site header (1024 × 574 at largest). So it just gets the largest image size, and lets the browser scale it down.

I think [`srcset`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#srcset) could help here, so the browser could pick the image that fits best.
