### ISSUE TITLE
Categories create overflow on mobile.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#157]
The categories don't look right on mobile. They should be left aligned (the button is but the text isnt) and they shouldn't introduce an overflow. Additionally the original designs have them horizontally scrollable. See [#419](https://github.com/WordPress/wporg-mu-plugins/issues/419)

| iPhone SE |
|--------|
| ![wordpress org_showcase-v2_(iPhone SE) (2)](https://github.com/WordPress/wporg-showcase-2022/assets/1657336/b1d1cfa9-28c5-4ce2-aa4e-f1bb5b6a965e) |

**Comment by ryelle** [comment]
Fixed this with https://github.com/WordPress/wporg-showcase-2022/commit/7c9ffa6db0d001c5edcf836b0143601a8f7548aa & https://github.com/WordPress/wporg-showcase-2022/commit/30eba141933665c5b5fd1e91aaaa98d79aae80e7
