### ISSUE TITLE
Limit the display of tags on site grid

### ISSUE THREAD

**Issue by ryelle** [WordPress/wporg-showcase-2022#158]
Pulling out of #151, since it's become a discussion

> jasmussen: Is it possible to limit the display of tags on this page to at most 3?
> jasmussen: Ideally that could help us avoid the eliding (...) of the text tht happens.

> ryelle: Should this be a content rule- limit chosen tags to <=3, or just the display here restricted in code?

> jasmussen: I'm happy to defer to content authors on the amount of tags to show. This is mainly an inquiry, can we restrict it just in code? If yes, then that would be great.

> StevenDufresne: I would limit it in code so we don't implement a limitation that leads to sparse archives or make content authors decide which categories are the most fitting.
> StevenDufresne: I also find the truncation distracting on mobile, and maybe should consider only showing 2 on mobile.

> jasmussen: We can also include a blanket 2-tag limitation.

**Comment by ryelle** [comment]
Currently, the cut off is based on available space, not number of tags.

See https://github.com/WordPress/wporg-showcase-2022/issues/136#issuecomment-1684339247

> It will be a max of 60% of the space available, but shrink down if a site has a long name. For example:
> <img width="434" alt="Screenshot 2023-08-18 at 3 15 22 PM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/80ff2f2d-52b0-407f-9a88-0184d5577f18">

If we switch this to a fixed count of tags, we'll probably still want that ellipsis just in case, since a long name could still cause wrapping:

<img width="426" alt="Screenshot 2023-09-18 at 11 57 30 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/01ffc4b2-fccb-4a62-98a9-a01bfa2b0b7c">

There isn't a simple hook to change the post-terms block, so I think a better approach would be to use CSS + nth-of-type, which also means we could do 3 tags on larger screens, and 2 tags on small.

**Comment by ndiego** [comment]
From an information perspective, I prefer seeing all the tags, even if they end up stacking. If they do stack, though, should the tags shift under the title and be left aligned?

<img width="411" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/f822f8f0-fa63-48e2-9e56-3f29e830c24e">

Another thought, what if these links were the category of the site and not the tags? This removes the issue of tag number entirely.

**Comment by ryelle** [comment]
All the tags will still be available on the single page, so they're not missing from the whole site.

If we wrapped the tags, it would make the item heights in the rows uneven.

<img width="1389" alt="" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/5ea3011f-d87b-4413-b897-afa3b77c6311">

Actually, I don't think this is the worst look, especially if they're always under the title…
 
<img width="1361" alt="Screenshot 2023-09-19 at 10 51 17 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/b2440f14-b8d4-404a-95c1-109bf8298569">

But back [in the original issue](https://github.com/WordPress/wporg-showcase-2022/issues/136#issuecomment-1664756667), design decided to truncate them, so I'd rather not change that now.
