### ISSUE TITLE
Total number of sites on homepage (Showcase v2)

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#159]
On the homepage of the v2 Showcase, the site number is 12. I believe this is because it's pulling the count from the grid. This number should be the total number of sites in the whole Showcase. cc @jasmussen to confirm.

<img width="581" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/e964660a-b9d9-4e2f-8887-521874900ae9">

**Comment by jasmussen** [comment]
Yes, good catch, and similar the number on search results should be the total number of results, not the results shown on the active page.

**Comment by ryelle** [comment]
It's displaying the total count for the current query, which in this case is 12 total featured posts. I'll see if I can override that for this one query.

> the number on search results should be the total number of results, not the results shown on the active page.

@jasmussen It should be, can you share a link where that's not working?
