### ISSUE TITLE
Filter dropdown causing scroll issues (Showcase v2)

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#160]
In testing the filters, I noticed that the scrolling menu caused the page height to expand, which led to more scrolling. This is best explained visually: 

https://github.com/WordPress/wporg-showcase-2022/assets/4832319/899442fc-79fd-4530-b84b-29b4b635f116

Also, I believe there should be a gap between the button and the menu when referencing the Figma file. cc @jasmussen to confirm. 

<img width="360" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/db8f28ca-1839-43d3-bcba-c19fd52f08bc">

**Comment by jasmussen** [comment]
Yep, there should be a 10px gap between the button opener and the dropdown, this is tracked in #151 as well.

**Comment by ryelle** [comment]
@ndiego The query filters PR was merged, can you check if that fixed the extra height on the page? If not, which browser are you using?

**Comment by ndiego** [comment]
@ryelle yes, this issue no longer exists with the latest merge. I'll close this out. Thanks!
