### ISSUE TITLE
Copy QA for Showcase v2 staging

### ISSUE THREAD

**Issue by thetinyl** [WordPress/wporg-showcase-2022#162]
These are some of the small copy edits I noticed when reviewing the staging site. There may be a couple more outstanding based on some additional considerations, but nothing that's a blocker to launch. 

### Showcase main page

- [x] add period after sub-copy under "Showcase" header

<img width="385" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/100625704/0a8e7eef-df94-4b07-aae5-072f3cb84b29">

### Submit a site page

- [x] make headers sentence case within body copy (Note: screenshot below doesn't reflect current site copy, just to be clear, I'm including for visual reference. 😄)

<img width="291" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/100625704/a9355a17-2057-46fa-9558-5b915e136713">

### All tags page

- [x] remove "the showcase" mention in main header
- [x] remove periods from sub-headers

<img width="423" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/100625704/d441b890-0c0e-4a0f-9265-b9c2ae9bb6f8">

**Comment by jasmussen** [comment]
Not sure if this is the best place to store copy feedback, let me know if somewhere else is better, but I noticed that for [the CUNY site,](https://wordpress.org/showcase-v2/the-city-university-of-new-york/) we should update the URL in the copy:

<img width="289" alt="Screenshot 2023-09-21 at 09 47 15" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/fe370d72-a654-4832-b8aa-822a36b98011">

<img width="146" alt="Screenshot 2023-09-20 at 18 34 12" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/11735539-4213-4e8d-aee3-100df77aa885">

**Comment by thetinyl** [comment]
Thanks @jasmussen!

> Not sure if this is the best place to store copy feedback, let me know if somewhere else is better

I'm not sure either. Since the Showcase site pages can be updated through the editor vs. hard coded, perhaps it could help to log all that kind of copy feedback in another issue for me to look at together? Takes one more thing off of Meta team's focus list.

**Comment by ryelle** [comment]
> Since the Showcase site pages can be updated through the editor vs. hard coded, perhaps it could help to log all that kind of copy feedback in another issue for me to look at together?

Yes, that would be great :)

The submission page and "thanks" page are also both in the editor, so those can also be updated without dev help, if anything else needs doing there.

**Comment by thetinyl** [comment]
> The submission page and "thanks" page are also both in the editor

Oh! I didn't realize. So for future reference... is it just the homepage and all tags page that are hard-coded?

**Comment by ryelle** [comment]
Yeah. The archive pages are also technically hard-coded, but there isn't really copy there to update. The local footer (the two CTAs) is hard-coded since it's shared across multiple pages. The "log in" message is also hard-coded since we need to load it conditionally (that could be moved, but it's easier this way). Everything else _should_ be editable, my aim was to default to the editor when feasible.
