### ISSUE TITLE
Copy: Update the body text of sites to use blocks, notably to fix quotations

### ISSUE THREAD

**Issue by jasmussen** [WordPress/wporg-showcase-2022#170]
If you go to https://wordpress.org/showcase-v2/noma/, you'll see this quote styles:

<img width="952" alt="Screenshot 2023-09-21 at 09 56 18" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/d59549bc-c711-46a2-bd0d-db1aa37fb2a4">

If you go to https://wordpress.org/showcase-v2/the-walt-disney-company/, however, you'll see this quote style:

<img width="739" alt="Screenshot 2023-09-21 at 09 57 15" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/fdfbca53-cdbc-436c-965c-0d06d3a8955a">

The latter is an unstyled `blockquote`, indicating the copy is written in the classic editor and is not comprised of blocks. The former is a styled Quote block.

Separately, we can discuss whether the quote style for blocks is actually ideal, here's an alternate take that could work:

<img width="776" alt="Screenshot 2023-09-21 at 09 59 35" src="https://github.com/WordPress/wporg-showcase-2022/assets/1204802/69cce3e5-b64d-463d-9ee2-ab8c71b63660">

The above is:

* Uncolored (i.e. `currentColor`) left border
* 2px left margin
* No font family change, no font size change, no font weight change
* No font size or weight change on the citation

**Comment by ryelle** [comment]
@jasmussen I've updated Disney. Do you want this quote style change to apply to all sites, or is that a showcase specific style? and are you proposing an idea for designer feedback, or asking me to implement that?

**Comment by jasmussen** [comment]
Thank you! I do think we need the quote style change to be the same across the whole website, but because of that perhaps we shouldn't make that change at the moment. The current style is okay for now. 

This is copy territory, and I'll defer to @thetinyl on next steps here, but it seems like for the Disney inclusion (which also needs a new screenshot), do we even need that paragraph to be a blocquote? Can it just be body text?

**Comment by thetinyl** [comment]
> it seems like for the Disney inclusion (which also needs a new screenshot), do we even need that paragraph to be a blockquote? Can it just be body text?

Short answer: Yes, it would need to appear as a quote since it's a quote. 

At a glance, it looks like this was pulled directly from their site (it refers to them as "we"). It also looks like that blurb has been updated recently on their site so should probably reflect that change here since it's now a misquote. 

But if it offends as a quote, I can adjust when I get to reviewing the rest of the sites after all the featured content is wrapped.

**Comment by jasmussen** [comment]
It doesn't offend as a quote, no, but I wonder if that quote can stand alone without any intro or citation. It seems a bit lonely or terse?

**Comment by thetinyl** [comment]
> It seems a bit lonely or terse?

I'll take a closer look when I do a broader copy QA of the imported sites. 👍

**Comment by ryelle** [comment]
I'm going to close this issue since site copy is being tracked in a spreadsheet (and it looks like we might remove Disney anyway). The quote styling is tracked in #206.
