### ISSUE TITLE
Breakpoint change

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#171]
Live version has 3 columns after a breakpoint (1440px). We discussed having that breakpoint at 1920px, as in design.

1. What bugs can happen if we do that?
2. Is it lot of work to do it?

<img width="702" alt="Screen Shot 2023-09-21 at 15 31 00" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/ca14eef8-d7ce-40bc-855d-dbae8fa6cdb5">

CC: @jasmussen @ryelle

**Comment by ryelle** [comment]
@marko-srb This is pretty trivial to change, so it's more a question of what works well.

The difference between 1440 and 1920 feels like a lot— right before the cutoff, the images will be 830x460, which is quite large. We could do somewhere in the 1600-1700 range? Then the images would be around 700x400. That would catch 60% of all desktop screen sizes (and that's assuming people use full-width viewports).

**Comment by ryelle** [comment]
nope! we can go with 1600 👍🏻
