### ISSUE TITLE
Featured home sites / Visual Content changes 

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#173]
Background color and website screenshot changes to the home page websites. 
These are mostly to be done by Marko (me), with exception of the hero section.
—

**1. Hero section sites should be:**
http://5yn3rgy.com/
http://about.fb.com/news
http://nytco.com/
http://gv.com/
http://orchestremetropolitain.com/
http://ageofunion.com/

@ryelle do you think you can add these, while I'd edit screenshots and colors for those. 👆🏻

**2. Featured sites.** 

Ubisoft Quebec.
- [x] Color code for background
- [x]  mobile ss is thicken

Women in Soccer.
- [x] For now use better ss.
- [x] Remove from home page. (later after the launch)
- [x] mobile ss is thicken

AD Dal Pozzo
- [x]  Website have changed their look/design. But the older screenshot are still present at their shop page. So consider changing the link of the site into the shop link: https://shop.arredodalpozzo.it/
- [x]  update ss and color

PichiAvo
- [x] Change screenshots and background color code.

Noma
- [x] Change background color

The Line Hotels
- [x] Change mobile ss

Qualtrics
- [x] For now use better ss.
- [x] Remove from home page.

Caeserstone
- [x] Change background color

Dita
- [x] Change bg color
- [x] https://wordpress.org/showcase-v2/dita/ cc: @ryelle this lacks border (or if color is the issue, bg color is being changed and it will solve this)
- [x] Mobile ss is thicken /

Tonal
- [x] Change bg color
- [x] Change mobile ss

Rolling Stone
- [x] For now use better ss.
- [x]  Remove from home page. (later after the launch)

Method
- [x] Remove from Showcase as it is not WP site

Sites to replace above ones (later after the launch)
https://designmuseum.dk/
https://www.noguchi.org/
https://www.moooi.com/en/
https://www.landia.com/

CC: @jasmussen let's not overlap any of the changes above, in case you were thinking about these. :)

**Comment by ryelle** [comment]
@marko-srb I think you can edit everything you've mentioned here. To add sites to the "hero" section, just make them sticky.

I'm going to unassign myself, but feel free to ping me if you have any other questions.

> Dita lacks border

I think you've fixed this, since I see the border again, but answering just to share info— the border is a 10% #1e1e1e, so if the background is dark, it might appear invisible.
