### ISSUE TITLE
Make the mShots loading icons smaller.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#177]
Follow-up to https://github.com/WordPress/wporg-showcase-2022/pull/172.

`One thing to follow up on, not urgent: the spinner should be 16x16px. Intentionally small!` - [Source](https://github.com/WordPress/wporg-showcase-2022/pull/172#issuecomment-1732265941)

**Comment by jasmussen** [comment]
An addendum, I'm assuming the preloading of mshots is local here to the showcase, but in case it isn't, it's perfectly fine to use this spinner at this size for everywhere across the site where we use mshots.
