### ISSUE TITLE
Swap button styles on footer CTAs

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#181]
Since the primary user action after visiting the Showcase should be "Getting WordPress", let's swap the button styling on the footer CTAs. 

**Current**
<img width="1478" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/6a1d8821-79f4-4508-b5ae-a2d292cc19cc">

**Proposed**
<img width="1460" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/8828fd8a-15d9-4bfb-92c1-36650ab6ddc8">

**Comment by ryelle** [comment]
This was tracked in #174 & fixed with #176 last night, "Get WordPress" should be primary on staging now.
