### ISSUE TITLE
Update labels and dots on Browse page 

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#188]
The labels above each section make it hard to understand the type of taxonomy you are viewing when glancing quickly. Perhaps we should simplify and just list the type of taxonomy for easier scanning.

Also, the dots between flavors and tags feel a bit out of place. Perhaps remove them entirely. 

I put together a quick mockup. The labels are updated to be `20px` and bold, but I defer to design (cc @marko-srb, @jasmussen)

| Current | Proposed |
| ---- | ---- |
| <img width="1536" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/51b2ab9a-9fd1-4746-8a78-9f7ea4d71ee1"> | <img width="1373" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/51de3a09-9e13-4c5c-a7c2-62bd6643f93d"> |

**Comment by jasmussen** [comment]
I don't have a very strong opinion here, though I will note that the existing verbiage has some character that I appreciate. I don't know that the glanceability of the _heading_ here is what's important, but rather the glanceability of each item below.

Doesn't see urgent, and I'm happy to go with either, but would appreciate input from Marko as I believe he added the character intentionally.

**Comment by ndiego** [comment]
@marko-srb what are your thoughts here? I can create a PR either way. Thanks!

**Comment by marko-srb** [comment]
> Also, the dots between flavors and tags feel a bit out of place. Perhaps remove them entirely.
We need that differentiation in my mind. :)  
It is enough confusing that we have various ways of wayfinding. So visually separating them would be nice. But if you feel nicer about them being on bottom, sure, go for it. :) 

I am ok with 20pt font (large). Just put it in regular, not bold. Thanks.

<img width="976" alt="Screen Shot 2023-09-28 at 16 27 44" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/a74ee6fa-936f-4069-9aee-d67e1d4a2ad5">

**Comment by ndiego** [comment]
Perfect, on it!
