### ISSUE TITLE
Size of the dots in hero section to match to other dots in sub-footer section

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#189]
Is there a way we can pull off this with pure CSS instead of an image? Know there have been discussions before, but to see if that's doable...

Can we make these dots: 
<img width="1710" alt="Screen Shot 2023-09-27 at 22 40 08" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/a1b0d3cc-c31c-4d2b-81cb-83e02cd3881a">

Seem same size as these dots:
<img width="1711" alt="Screen Shot 2023-09-27 at 22 40 15" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/f6aac51e-e244-474f-a02c-b3f061db8929">

**Comment by ryelle** [comment]
> Is there a way we can pull off this with pure CSS instead of an image? Know there have been discussions before, but to see if that's doable...

Not really — not without having the corners misaligned or dots getting cut off (I tried). I really don't want to go down the path of changing the implementation for this again when we finally got it working. but I'm happy to change out that SVG for a new one if you want to update it.

Here's what it would look like if I just change the size of the dots, but I don't know if you'd also want to update the spacing between dots.

![Screen Shot 2023-09-27 at 16 48 52](https://github.com/WordPress/wporg-showcase-2022/assets/541093/16156c78-b3ec-46c5-b735-617ec79dabab)

**Comment by marko-srb** [comment]
@ryelle 

Thanks. If you can put this version live, that's good, as long as previous fallback is somewhere to be found? So we can revert easily. 

This works well for what we need, but in case someone wants it reverted, we need the current version saved, or guide on how to put it back. Let me know if I can help with that record/tracking somehow.

Thank you!

**Comment by ryelle** [comment]
If this needs to be undone, [the commit](https://github.com/WordPress/wporg-showcase-2022/commit/d6963b0d7dd5988e5d713ca3fe37f4b93726875f) can be reverted or just the `dots-hero.svg` file can be updated to set the `r="2.5"` back to `r="4"` — all I did was a find & replace to update this 🙂
