### ISSUE TITLE
Post/website thumbnail hover state

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#191]
When a user hovers on the website/post thumbnail, the hover state should activate the link below as well. Underline it and blueberry. Same as if you were to only hover a link itself. 

screenshot for reference
<img width="845" alt="Screen Shot 2023-09-27 at 22 59 03" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/28038a5e-6f4f-49d3-87e4-4514657d9f72">

Or is there a rationale that makes this a bad approach?

CC: @jasmussen

**Comment by jasmussen** [comment]
I understand the motivation: it's the same link, why have two destinations? But to Kelly's point, this is non-trivial to implement. You could potentially explore a li:hover, but I think that might be misleading too. I personally think it's okay as-is.

**Comment by marko-srb** [comment]
In that case, let's close this one. Thanks for the clarification. I'll close it shortly.
