### ISSUE TITLE
Can we express borders on thumbnails more?

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#192]
Can we increase visibility of borders on site/post thumbnails more?

Here's suggestion, that needs review:

![thumbnail-border-opacity](https://github.com/WordPress/wporg-showcase-2022/assets/111751264/b87302e2-a57b-49aa-ace2-c7e42966284b)

@jasmussen what do you say here?

**Comment by jasmussen** [comment]
I _believe_ this would be mostly easy to implement, since it appears to be a dedicated CSS variable (`--wp--custom--wporg-site-screenshot--border--color: rgba(30, 30, 30, 0.1);`). I think the current works, but I think the latter works too, and would be happy to go with your instinct here.

**Comment by marko-srb** [comment]
After a little chat we gave up on this one. Apologies. Its good as is.
