### ISSUE TITLE
Hide the Featured category on the homepage

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#195]
We'd like to use this category only for practical reasons, so that we can manually affect which site goes to the home page. In that light, we'd love if this category is hidden from the home page. 

Since we will temporarily add categories on the places of tags, featured shouldn't appear below site screenshots/post thumbnails, or at least not on the home/landing page.

<img width="1716" alt="Screen Shot 2023-09-28 at 11 44 45" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/b20427d9-f3d4-4b4f-933a-02557b49b843">

**Comment by ndiego** [comment]
@ryelle how hard would it be to hide Featured entirely? So it is just an internal category that is used for site sorting, but not something that the public sort/search by. That would solve this.

**Comment by ryelle** [comment]
Sure, that would be easier than conditionally hiding it on some pages.

**Comment by ndiego** [comment]
> How hard would it be to hide Featured entirely? So it is just an internal category that is used for site sorting, but not something that the public sort/search by. That would solve this. 
>
> Sure, that would be easier than conditionally hiding it on some pages.

@marko-srb @jasmussen are you comfortable with this approach?

**Comment by jasmussen** [comment]
Sure. To me, Featured means it's in the homepage. So it's a utility class. I'm fine with hiding it.
