### ISSUE TITLE
Single page: Can we move/align quote block on the left edge with other text

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#206]
This alignment on the left, same as other paragraph elements should work well, as quote has different font, and the vertical line.

<img width="976" alt="Screen Shot 2023-09-28 at 16 27 44" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/6a89cdc3-4bb1-4b93-8107-c3c0479e4c48">

CC: @jasmussen

**Comment by jasmussen** [comment]
A  greed. I'm assuming you are comparing it with this indentation:

![Screenshot 2023-09-28 at 16 35 16](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/ee5f545f-ce5d-4940-a28e-ee441b8a30fd)

Note that this quote style is global, so it is also present in news, but curiously, the extra margin is not present there:

https://wordpress.org/news/2023/09/openverse-wins-the-2023-oeg-open-infrastructure-award/

![Screenshot 2023-09-28 at 16 37 41](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/ac8b0e34-ca1f-4df7-b204-50cfcf88d4ea)

So this may be a local bug to fix here?

**Comment by ryelle** [comment]
News is not part of the shared system. That said, [this example is & looks like News](https://wordpress.org/documentation/article/where-to-find-wordpress-help/#brainstorming-search-terms), so maybe something is going on with Showcase specifically.

Are the only changes the left margin & 1px border? If there are other changes, can you share a figma link so devs can reference it?

**Comment by jasmussen** [comment]
Oh, thank you for the clarification. I assumed it was inherited as it seems close enough.

That said, I think a solid first step is to just add `margin-left: 0; margin-right: 0;` to the quote, right now it appears inherited from the browser:
![Screenshot 2023-09-29 at 09 39 12](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/b486d8ec-bc09-4d78-91d9-a46fadcb78ea)
![Screenshot 2023-09-29 at 09 39 16](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/89b97162-eadd-42be-a255-a9d5ff3c4257)

**Comment by marko-srb** [comment]
Agreed with Joen, we can do that as the first step and see if it works...

**Comment by ndiego** [comment]
>That said, I think a solid first step is to just add margin-left: 0; margin-right: 0; to the quote, right now it appears inherited from the browser:
>
> Agree with Joen, we can do that as the first step and see if it works...

@ryelle I believe this can be fixed automatically by setting the Post Content block to "Inner blocks use content width" (i.e. `"layout":{"type":"constrained"}`). This adds the class `is-layout-constrained` which knocks out the browser margin.
