### ISSUE TITLE
Add breadcrumbs to all pages

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#208]
Here are the breadcrumbs, and they should be found on 'search results' as well...

Taxonomy for search results: "Home / Showcase / Search results"

![image](https://github.com/WordPress/wporg-showcase-2022/assets/111751264/d26c7d17-fca9-4892-9253-0e1f06ed5e4d)

CC: @jasmussen

**Comment by ryelle** [comment]
> Home / Showcase / Search results

Technically "home" and "showcase" would be the same URL (`https://wordpress.org/showcase/`), do you mean for Home to be `wordpress.org`?

This is different from the developer reference, which [uses "Home" to mean developer.wordpress.org](https://developer.wordpress.org/redesign-test/reference/functions/get_sitestats/).

**Comment by ryelle** [comment]
This also adds some duplicate links pretty close to each other— the Showcase link the local nav bar (black background) would be the same as the middle breadcrumb, and if "Home" is meant to be wp.org, that's the same as the W logo.

<img width="634" alt="Screenshot 2023-09-28 at 4 43 23 PM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/f7a620a1-0726-4d6d-8b13-427854de57b7">

**Comment by ryelle** [comment]
This issue also made me think about how these bars should all work on scroll, so I left a comment about that over on this issue https://github.com/WordPress/wporg-main-2022/issues/263#issuecomment-1740112122

**Comment by jasmussen** [comment]
Thanks for the ping. I believe the breadcrumbs as Francisco designed them has Home being the main index for that page. So it should likely be:

```
Showcase
Home / Tags
```

in the example above. And in this case, both "Showcase" and "Home" links would link to the same place.

**Comment by marko-srb** [comment]
Oh, my bad then. Apologies. 

Joen's suggestion seems right. I am not sure why we have 'Showcase' one on top another. It makes sense if this stays ticky though, while top nav doesn't. 

Anyhow, let's proceed that way and chat with Francisco about your comment Kelly, once he's back:

![image](https://github.com/WordPress/wporg-showcase-2022/assets/111751264/39cbd891-a027-441a-ae11-1242aab5b17a)


Thanks!

**Comment by ryelle** [comment]
Okay, I started to implement this and I'd like to check in.

To start, here are some easy ones, I think these are all fine.

All sites page, no filters
![all-sites](https://github.com/WordPress/wporg-showcase-2022/assets/541093/8afd2bcf-1fd0-4e7b-9325-98315da68e39)

A search result (the wordpress meaning of search)
![search](https://github.com/WordPress/wporg-showcase-2022/assets/541093/dc52c905-8bef-4fcb-9e75-764daef41ed7)

The submission page
![submit](https://github.com/WordPress/wporg-showcase-2022/assets/541093/64fd5476-f6db-4e4e-abc5-3b54ccc2c54e)

A single site
![single](https://github.com/WordPress/wporg-showcase-2022/assets/541093/2ab4afb2-8e25-4ee4-9ca6-bf22b5fd26fa)

---

These are not handled by your mockups, but I've used my judgement:

Archive, one category selected
![single-cat](https://github.com/WordPress/wporg-showcase-2022/assets/541093/05b59ba1-31ce-48b7-bcb3-4d0497b51545)

Archive, two filters applied
![multi-cat](https://github.com/WordPress/wporg-showcase-2022/assets/541093/75f4d946-9857-44a9-9c82-a3bd919b782e)

---

These are probably wrong…

"Browse" is probably not a great title for this page, but is contains more than just tags so I don't think "Tags" works either. This can be changed in the site content though, it's not a blocker for the code.
![browse](https://github.com/WordPress/wporg-showcase-2022/assets/541093/c9b5c91d-edd9-47e6-b3de-4def8c008cd8)

The Thanks page should probably not have this? Or it should be dark. Should the "current page" be faked to be the submission page?
![thanks](https://github.com/WordPress/wporg-showcase-2022/assets/541093/9a782074-6e09-467a-b9db-70d8e93f2705)

Any conversation about stickiness should stay in [the other issue](https://github.com/WordPress/wporg-main-2022/issues/263#issuecomment-1740112122), though I was hoping to find a solution before my sabbatical, which is before Francisco gets back.

**Comment by jasmussen** [comment]
In general, looks good.

This is more of a note for @pablohoneyhoney, I think the individual site feature loses a little character with the white bar above it. I also think it's acceptable and the consistency of the bar helps, so I don't know that there's an easy fix there, outside of maybe just not showing the breadcrumb bar on this page? Or maybe having a dark version?

> "Browse" is probably not a great title for this page, but is contains more than just tags so I don't think "Tags" works either. This can be changed in the site content though, it's not a blocker for the code.

Could it be "Archive"?

> The Thanks page should probably not have this? Or it should be dark. Should the "current page" be faked to be the submission page?

Related to the single feature, I wonder: is it possible for us to have an inverted breadcrumb bar, same color as the 1st row, just for the single site pagess and the submission success page?

**Comment by jasmussen** [comment]
I'll defer to @marko-srb if he prefers light or dark, but I think dark could work for both of those.

"Filters" sounds good to me.

**Comment by marko-srb** [comment]
This one to close as #217 is fixing this one...
