### ISSUE TITLE
Emphasize external/site link visibility on single posts

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#214]
We should emphasize the website external link on single posts. Do you think an underline works well here? 

<img width="1353" alt="Screen Shot 2023-09-28 at 21 57 20" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/6cd30441-fc50-4357-a9bc-832cde43579d">

@jasmussen

**Comment by jasmussen** [comment]
I do, yes, this seems worth trying as the first thing.
