### ISSUE TITLE
`wporg-showcase` has custom feed code, do we need it?

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#22]
The wporg-showcase theme has some custom rss feed code. Do we still need it?

**Example**:
https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-showcase/feed-extras.php 

There are more references in [functions.php](https://github.com/WordPress/wordpress.org/blob/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-showcase/functions.php).

**Comment by tellyworth** [comment]
Interesting! I wonder if anyone uses it.

It seems to just add custom screenshot and url elements to the feed. If that's genuinely all it does then there's no need for a custom feed file; the https://developer.wordpress.org/reference/hooks/rss2_item/ hook should make that possible. Maybe there's some reason it was done this way.

I could take a quick stab at moving it to a hook if you like. That might(?) make it slightly easier to incorporate new screenshots (featured image?).

**Comment by StevenDufresne** [comment]
Please do!

**Comment by StevenDufresne** [comment]
@tellyworth Do you still have bandwidth to look into this?

**Comment by dd32** [comment]
> Interesting! I wonder if anyone uses it.

I doubt. I did some archeology on the source of it:
> Date: 2009-03-20
> Message: custom showcase feed to get at the screenshot and domain of a site

**Comment by StevenDufresne** [comment]
I'm not a fan of again tickets. I'm going to close this until there's a reason to open it again.
