### ISSUE TITLE
Improve archives page title.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#221]
Should we improve the title of the archives to be more specific to the showcase?

If we follow the theme directory and plugin directory pattern, it would look something like:
`WordPress Sites | WordPress.org`

**Current**

<img width="817" alt="Screenshot 2023-10-04 at 12 38 11 PM" src="https://github.com/WordPress/wporg-showcase-2022/assets/1657336/4cc6935c-b4b1-4168-85dd-2350e131983c">

**Comment by ryelle** [comment]
I've updated the page title to "All sites" which matches how we talk about it on the site itself.

in `title` tag
<img width="225" alt="Screenshot 2023-10-04 at 11 30 50 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/cdc4748e-ae13-4b74-af1f-51e228caf906">

OpenGraph preview
<img width="457" alt="Screenshot 2023-10-04 at 11 31 09 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/3d6b72f8-89b7-4d10-804a-ebc539e450f5">

Does that work?

**Comment by ndiego** [comment]
> I've updated the page title to "All sites" which matches how we talk about it on the site itself.

That looks good IMO.

**Comment by ndiego** [comment]
@renintw given #243, this would be updated to  "All sites – WordPress Showcase | WordPress.org", right?

**Comment by renintw** [comment]
Completed through https://github.com/WordPress/wporg-showcase-2022/pull/253
