### ISSUE TITLE
Add taxonomy counts to the filter dropdowns

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#225]
User feedback indicated that the "Apply" button was a bit confusing. The fact that it includes "(x)", the user thought that was how many sites were included in the selected taxonomy. It was not clear that this number was how many taxonomy terms were selected. 

Perhaps one solution is to add site counts for each term. It makes the filter dropdown more cluttered, but perhaps it provides more context to the user. 

<img width="722" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/094a1e58-3cc8-4a87-ad4a-7b4bc0fc78ef">

cc @jasmussen @marko-srb

**Comment by jasmussen** [comment]
It could be "Apply 3 tags". 

Or we could just make it so you can only ever pick a single tag at a time. 

Both seem valid options and could hopefully be quickly implemented.

**Comment by ndiego** [comment]
> It could be "Apply 3 tags"
> Both seem valid options and could hopefully be quickly implemented.

Agreed. Just for visual reference, this is what that would look like for categories. 

<img width="370" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/11c18cd9-b27d-4a63-9c5a-64d0fd5c09b8">

**Comment by StevenDufresne** [comment]
I don't like "Apply 3 categories" as a solution. It creates too much change in the user interface. I would prefer we do more user testing to see if this is a problem for many. I vote for counts on the tags/categories as the first iteration.

**Comment by ndiego** [comment]
> I don't like "Apply 3 categories" as a solution.

It does make the UI feel cluttered. 

> I vote for counts on the tags/categories as the first iteration.

This would also be my vote since it conveys more relevant information to the user and may also address the confusion that prompted this issue. While a minor benefit, this approach of listing site counts is also in keeping with the current Showcase.
