### ISSUE TITLE
Improve the consistency of page `<title>`s

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#243]
> Page `<title>`s are inconsistent about whether they include (or end in) "WordPress Showcase"; can we define and use a consistent pattern throughout which includes this?

I broke out this comment from #234. 

The `<title>` for individual site pages ends in `– WordPress Showcase | WordPress.org` ([example](https://wordpress.org/showcase-v2/nasa/)). But all other pages end in just ` | WordPress.org`. There is no mention of "WordPress Showcase". Not sure how we want to resolve this, but I think the titles should mention "WordPress Showcase" once you get past the Homepage.

Let's also update the `<title>` on the Homepage to the following. This matches the thumbnail image and the subtext on the Homepage.

```
Star-studded sites built with WordPress | WordPress.org
```
 
cc @eidolonnight 

> [!Note]
> Related: https://github.com/WordPress/wporg-showcase-2022/issues/221

**Comment by thetinyl** [comment]
> I think the titles should mention "WordPress Showcase" once you get past the Homepage.

For this iteration, I agree with this direction (for what it's worth 😄). 

Generally, however, I wonder if "WordPress Showcase" is resonant enough. Just peeping at a few competitors, seems like they're leveraging that space differently. Ex: "Squarespace Website Examples - Made with Squarespace", "Portfolio Website Examples and Design Ideas" (this is Wix), "Shopify Ecommerce Store Examples".

**Comment by renintw** [comment]
> Let's also update the <title> on the Homepage to the following. This matches the thumbnail image and the subtext on the Homepage. Star-studded sites built with WordPress | WordPress.org

Done updating.
ps. This can be updated in Dashboard > General Settings.

<img width="2676" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/18050944/9b15b8ea-bb06-429f-b981-6395d3f0ecd5">

---

> Not sure how we want to resolve this, but I think the titles should mention "WordPress Showcase" once you get past the Homepage.

| | Homepage | Other pages |
| -- | -- | -- |
| Current showcase sites | The Best WordPress Sites in the World &#124; WordPress.org | Bi-Rite Market Showcase &#124; WordPress.org |
| News | WordPress News – The latest news about WordPress and the WordPress community | WordPress 6.4 Beta 3 – WordPress News |
| Theme Dir | WordPress Themes &#124; WordPress.org | Twenty Twenty-Three - WordPress theme &#124; WordPress.org | 
| Pattern Dir | Block Pattern Directory &#124; WordPress.org | Centered image with two-tone background color – Block Pattern &#124; WordPress.org |
| Plugins Dir | WordPress Plugins &#124; WordPress.org | WPZOOM Portfolio – WordPress plugin &#124; WordPress.org |

From looking at other sites, it seems reasonable to mention "WordPress Showcase" once moving past the homepage.

**Comment by renintw** [comment]
@ndiego After taking a closer look into the code, I realized that the title behavior of other sites like the Pattern, Plugin, and Theme Directory is consistent with the current showcase. That is, the titles for home, tags, and categories pages all end with `| WordPress`, and only on Single Post Pages (i.e., individual site pages in the showcase here) do they display `- WordPress theme/plugins/pattern.` I apologize for not noticing this particular aspect of these sites during my initial review.

Given this, do you think a change is still necessary? I'm inclined to be conservative. Although appending "- WordPress Showcase" to everything other than homepage seems neat and uniform, I'm uncertain if the original title setup was discussed and decided upon in the past.

**Comment by ndiego** [comment]
> I'm uncertain if the original title setup was discussed and decided upon in the past.

This is a great question. I am not sure. Any ideas @StevenDufresne @eidolonnight?

**Comment by renintw** [comment]
some examples for reference

| Current <Title> | Pattern Directory | Showcase-v2 |
|-|-|-|
| Home page | Block Pattern Directory &#124; WordPress.org | Star-studded sites built with WordPress &#124; WordPress.org |
| Single post page | {Single post title} – Block Pattern &#124; WordPress.org ([link](https://wordpress.org/patterns/pattern/centered-image-with-two-tone-background-color/)) | {Single post title} – WordPress Showcase &#124; WordPress.org |
| Category page | Block Patterns:{Category Term} &#124; WordPress.org ([link](https://wordpress.org/patterns/categories/gallery/)) | Sites categorized as “{category term}” &#124; WordPress.org |
| Tag page | Tag page seems to be overridden, if there's any, the title should be similar to the one on the category page. | Sites tagged as “{tag term}” &#124; WordPress.org |
| Search result page | Block Pattern Directory &#124; WordPress.org ([link](https://wordpress.org/patterns/search/Centered/)) | Sites filtered by: {search term} &#124; WordPress.org |
| Page post type | {Page Title} &#124; WordPress.org ([link](https://wordpress.org/patterns/about/)) | {Page Title} &#124; WordPress.org ([link](http://localhost:8888/browse/)) |
| Author page | Block Patterns by {author name} &#124; WordPress.org ([link](https://wordpress.org/patterns/author/richtabor/)) | {Author name} &#124; WordPress.org ([link](https://wordpress.org/showcase-v2/author/ndiego/)) |

**Comment by StevenDufresne** [comment]
> > I'm uncertain if the original title setup was discussed and decided upon in the past.
> 
> This is a great question. I am not sure. Any ideas @StevenDufresne @eidolonnight?

Not specifically for the Showcase.

**Comment by ndiego** [comment]
Let's move forward with the following change if we can @renintw. The Pattern directory setup includes "Pattern" in most of the titles, so there is some context. We don't have that for the Showcase, so the following adds context will keeping things inline with the Pattern directory:

| Current <Title> | Pattern Directory | Showcase-v2 |
|-|-|-|
| Home page | Block Pattern Directory &#124; WordPress.org <br> Block Pattern Directory &#124; Page 2 &#124; WordPress.org ([link](https://wordpress.org/patterns/page/2/)) | Star-studded sites built with WordPress &#124; WordPress.org |
| Single post page | {Single post title} – Block Pattern &#124; WordPress.org ([link](https://wordpress.org/patterns/pattern/centered-image-with-two-tone-background-color/)) | {Single post title} – WordPress Showcase &#124; WordPress.org |
| Category page | Block Patterns: {Category Term} &#124; WordPress.org ([link](https://wordpress.org/patterns/categories/gallery/)) | Showcase sites categorized as “{category term}” &#124; WordPress.org |
| Tag page | Tag page seems to be overridden, if there's any, the title should be similar to the one on the category page. | Showcase sites tagged as “{tag term}” &#124; WordPress.org |
| Search result page | Block Pattern Directory &#124; WordPress.org ([link](https://wordpress.org/patterns/search/Centered/)) | Showcase sites filtered by: {search term} &#124; WordPress.org |
| Author page | Block Patterns by {author name} &#124; WordPress.org ([link](https://wordpress.org/patterns/author/richtabor/)) | Showcase sites by {author name} &#124; WordPress.org ([link](https://wordpress.org/showcase-v2/author/ndiego/)) |
| Page post type | {Page Title} &#124; WordPress.org ([link](https://wordpress.org/patterns/about/)) | {Page Title} &#124; WordPress.org <br>{Page Title} &#124; Page {current page #} of {total page #} &#124; WordPress.org ([link](http://localhost:8888/browse/)) |
| Archive page (the rule is identical to the Page post type) | Archive page = Homepage. | All Showcase Sites &#124; WordPress.org <br>All Showcase Sites &#124; Page 2 of 13 &#124; WordPress.org (updated in #221) |

**Comment by eidolonnight** [comment]
Sorry to chime in late. I wasn't aware we were changing the page title as part of the redesign. As for the recommendation, "star-studded" isn't particularly internationally friendly. Also, my general advisement for these titles is to consider tab size. That is a long title. @thetinyl perhaps you can provide some alternatives?

**Comment by ndiego** [comment]
<img width="330" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/890bf111-7bbc-4635-b2d7-49cd0ff09c34">

I just recommended this given the screenshot above. "The Best WordPress Sites in the World" is kind of a loaded statement. There are definitely other WordPress sites that we have not seen that might be "better". 😅

Regardless, this is something we can easily change in the Admin of the site itself, so no code changes are needed for the primary site title.

**Comment by thetinyl** [comment]
> Also, my general advisement for these titles is to consider tab size. That is a long title.

@eidolonnight I think the length is actually fine. Seems like, as long as it's within 600 pixels, it should be good/is unlikely to be truncated. 

Some alternatives to consider based on the sentiment of what's currently there or taking a cue from competitors (for now, anyway):

1. Beautiful websites built with WordPress | WordPress.org
2. Website examples built with WordPress | WordPress.org
3. WordPress Showcase website examples | WordPress.org

> this is something we can easily change in the Admin of the site itself, so no code changes are needed for the primary site title.

If any of the above seem fine, I'm happy to toss them in there through the site Admin.

**Comment by renintw** [comment]
Reopon it since there's discussion onging.

**Comment by eidolonnight** [comment]
I think we should be bold and use "best" somewhere here. I agree with @ndiego :

> "The Best WordPress Sites in the World" is kind of a loaded statement. There are definitely other WordPress sites that we have not seen that might be "better". :sweat_smile:

If someone sees the Showcase and thinks "OMG I know sites that are way better than these" then _good_. It can be motivation for them to submit those sites. We have an issue with there being a low volume of high-quality submissions. Maybe this would encourage those.

That said, calling these the "Best WordPress Sites" diminishes what they are. These should be some of the best sites on the web, and they just happen to be built with WordPress. I'd recommend something like this as the page subtext (can be adapted for SEO title):

> The best websites, built with WordPress.

**Comment by ndiego** [comment]
I have updated the tagline. Are any additional changes needed to make this live @renintw?

<img width="845" alt="image" src="https://github.com/user-attachments/assets/a719eae3-968a-48d4-a9a9-397f1eb137ba">

**Comment by renintw** [comment]
@ndiego The change to the tagline only affects the title on the homepage, and I can see that it's already in effect.
![image](https://github.com/user-attachments/assets/8de3cf2f-e4f2-435c-bfde-15617b7efd36)

As for the homepage tagline, it's written in the code, and I think the reason is for i18n. If we directly apply the tagline there, it will always remain in English. That said, I found that Showcase has not been activated on the Rosetta sites, and I also haven't seen it on translate.wp.org.

**Comment by renintw** [comment]
Close as https://github.com/WordPress/wporg-showcase-2022/pull/278 has been shipped.
