### ISSUE TITLE
Hide tags with less than X sites on the Browse page

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#244]
> Can we kill/hide all tags with fewer than 3(?) members? E.g., https://wordpress.org/showcase-v2/tag/space/ isn't useful 😆

I broke out this comment from https://github.com/WordPress/wporg-showcase-2022/issues/234.

On most laptops, the site grid will have 2 sites per row, so I would recommend that we hide tags from the [Browse](https://wordpress.org/showcase-v2/browse/) page if the term has less than 2 sites. Thoughts @jasmussen @marko-srb? 

<img width="1397" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/4832319/9aa16dfb-cbeb-4fe3-984a-815c74ee49b2">

@renintw with the current tag implementation on [Browse](https://wordpress.org/showcase-v2/browse/), how hard would this be to implement? If it's easy, it would be great to get this in ahead of launch, but this could be punted to post-launch if needed.

**Comment by jasmussen** [comment]
For what it's worth, I'm reading this as more of an editorial effort than a technical one. That if you click a tag and you only get two results, that's not a good experience begging the question _why even have that tag in the first place_? I agree with this, and lean towards either finding a way to use that tag on more sites, or remove that tag entirely. Previously we had a lot of cases like these, including a tag called "Eyewear", which would have two sites I believe. 

If I'm getting this feedback right, it may have been from a previous iteration, however, where we did have tags with very few sites, but I can't see that anymore. The fewest sites we have in a tag now is 4:

![Screenshot 2023-10-12 at 08 28 57](https://github.com/WordPress/wporg-showcase-2022/assets/1204802/b5410b4b-ef7e-4a46-b61a-b2bc53a2c846)

You can still get to a place where you combine enough tags, categories and flavors that you get few or no sites. I think that's related to separate tag/category/flavor conversations, and is arguably _fine_.

**Comment by marko-srb** [comment]
Here are my 2cents: 


- If removing all tags from TAGS page with 2 sites as results — leaves us with 10 tags there, then this is bad to do. 
- In any manner, 101 entry simply cannot provide a joyful experience if you press on most of the tags in the TAG page. So its more of, do we kill the TAG page, at this moment in time, or not, for me.

—

Now personal thought: I think it should stay. And I think it is ok if users come back and say hey folks what do we need this for, to consider removing. Plus I think we hid the index (Tags page) well enough, so it will be rarely used. All in all, I wouldn't touch Tags page (other than hiding flavors) at the moment. Also keep in mind that this is more a subjective view. 


CC: @ndiego , @jasmussen

**Comment by marko-srb** [comment]
We also should match the URL to the name. 

Either 'filters' either 'browse'. But I was prefering simply calling them 'tags' or 'wayfinding'. Why? 

1. Filters we do have in the All sites, as taxonomy. 
2. Browse is kinda results to search

So this can be confusing.

I had this comment before, but didn't work because we have categories and flavors.

**Comment by ndiego** [comment]
> For what it's worth, I'm reading this as more of an editorial effort than a technical one. 
>  All in all, I wouldn't touch Tags page 

Great feedback everyone. Let's leave the Browse page as is, and we will do a more thorough audit of the tags to try and ensure all tags have at least two sites. I'll take care of this. 

Given this direction, I am going to close the issue.
