### ISSUE TITLE
Widows on mobile screen

### ISSUE THREAD

**Issue by renintw** [WordPress/wporg-showcase-2022#255]
As the [comment](https://github.com/WordPress/wporg-showcase-2022/pull/240#issuecomment-1767041864) brought up, we've got widows on mobile screen. If adding the `white-space: nowrap`, it would overflow. Perhaps we can break lines between different words (`text-wrap: pretty;` can achieve this), allowing for more words on the second line, or just change the content for the mobile screen.

The effect brought by `text-wrap: pretty;` 
<img width="376" alt="image" src="https://github.com/WordPress/wporg-showcase-2022/assets/18050944/59e74960-b5a3-415d-a5cc-7b43e57cb9b3">

**Comment by ryelle** [comment]
Closing this issue, looks like this has been handled in the parent theme as of https://github.com/WordPress/wporg-parent-2021/pull/119 — I see the nicer wrapping in Chrome (`pretty` is not supported in FF or Safari though).

<img width="374" alt="Screenshot 2024-01-08 at 11 18 27 AM" src="https://github.com/WordPress/wporg-showcase-2022/assets/541093/892c48a5-1002-4ffa-9dc9-0dc0503b1381">
