### ISSUE TITLE
Mast Head

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#26]
# Designs
![image](https://user-images.githubusercontent.com/1657336/200215073-1515f5f4-e2de-4767-9cb5-0fec7fad70dd.png)

**Comment by StevenDufresne** [comment]
@ryelle @adamwoodnz @renintw Would it make sense to import a new font "oswald" for "Showcase" or maybe use an SVG background of some sort?

**Comment by renintw** [comment]
I'm thinking we may need to import it for the rosetta sites, though SVG is easier to implement and helps to save some loading time and storage for users, especially when here is the only place that uses the font.

**Comment by ryelle** [comment]
> I'm thinking we may need to import it for the rosetta sites?

That's a good question, whether this is a title that will need translation or if it's more like a logo.

I was also thinking an SVG, though to be editor-first it would be an image block of some kind, not a background (…then you run into the issue that SVG uploads aren't allowed, but perhaps we can change that for trusted users).
