### ISSUE TITLE
Showcase breadcrumbs issue

### ISSUE THREAD

**Issue by marko-srb** [WordPress/wporg-showcase-2022#269]
There are two lines below breadcrumbs. See attached image. It is some form of a bug that doesn't affect the functionality, but still shouldn't be there. 

@ndiego Who should I cc to look into this? Thanks

CC: @WordPress/meta-design 
<img width="1578" alt="ss" src="https://github.com/WordPress/wporg-showcase-2022/assets/111751264/085b67aa-1955-499b-9fd2-66372a5a7f5c">

**Comment by ryelle** [comment]
This has already been reported here: https://github.com/WordPress/wporg-mu-plugins/issues/575, and has a fix in progress.

Closing as a duplicate.
