### ISSUE TITLE
Page title not visible in the local nav but as in a breadcrumb

### ISSUE THREAD

**Issue by fcoveram** [WordPress/wporg-showcase-2022#274]
I noticed that page title in the [site details](https://wordpress.org/showcase/tonal/) page in Showcase is not visible in the local as agreed in [wporg-mu-plugins#535](https://github.com/WordPress/wporg-mu-plugins/issues/535). Instead, the breadcrumb shows up with the correct path.

![Screenshot of page header of Showcase's site details page](https://github.com/user-attachments/assets/91dd034b-4fbe-4f29-89da-c8ba7405d65c)

The problem seems to be only in Showcase. The component looks and the scroll behavior works correctly in the [Requirements page](https://wordpress.org/about/requirements/) in the About section.

![Scroll down behavior of local nav in the Requirements page](https://github.com/user-attachments/assets/c385bc62-46c3-438c-8e29-f1585087932b)

**Comment by ryelle** [comment]
This was done in https://github.com/WordPress/wporg-showcase-2022/commit/6694d2df0b9ce9fb4c5b1f2e3894a902deb56ba1 & https://github.com/WordPress/wporg-showcase-2022/commit/9b057878ae29918a9d9c33dd6fa45eb8d3fa4125, which have (finally) just been deployed to production.
