### ISSUE TITLE
Update front page tagline 

### ISSUE THREAD

**Issue by ndiego** [WordPress/wporg-showcase-2022#277]
Following the discussion in [#161 ](https://github.com/WordPress/wporg-showcase-2022/issues/243#issuecomment-2344995509), let's update the tagline on the Front Page to: 

> The best websites, built with WordPress.

| Current | Proposed |
|-|-|
|<img width="769" alt="image" src="https://github.com/user-attachments/assets/914013f4-4dc3-47f7-8289-7a4e28c2c25a">|<img width="739" alt="image" src="https://github.com/user-attachments/assets/ecc54fcd-dc6c-4910-9a85-d6895d2833bd">|

**Comment by eidolonnight** [comment]
Yes, as stated in https://github.com/WordPress/wporg-showcase-2022/issues/243#issuecomment-2344679696 , these should be some of the best sites on the web, and they just so happen to be built with WordPress.

> The best websites, built with WordPress.
