### ISSUE TITLE
Links to external sites should have external link icon. 

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#42]
Feedback was given to add an external icon to links that navigate the user away from wordpress.org. 

We have one such occurrence in this theme:

<img width="718" alt="Screen Shot 2022-11-15 at 8 52 12 AM" src="https://user-images.githubusercontent.com/1657336/201792408-f1dbc733-d8d7-41f7-bcb7-f1914ef9565b.png">

**Comment by bengreeley** [comment]
@StevenDufresne What are your thoughts for an approach to handle this sitewide? IMO it would be great if we had some global logic that could be applied to all sites, but I'm curious of how you were thinking of approaching this.

**Comment by StevenDufresne** [comment]
>@StevenDufresne What are your thoughts for an approach to handle this sitewide? IMO it would be great if we had some global logic that could be applied to all sites, but I'm curious of how you were thinking of approaching this.

I have a PR open for it in the parent. I originally approached it a bit narrow-minded. I think @ryelle's [suggestion](https://github.com/WordPress/wporg-parent-2021/pull/53#discussion_r1023202390) to use CSS attribute matching should work pretty well.

**Comment by StevenDufresne** [comment]
I'm going to close this and just wait for the parent PR to land:
https://github.com/WordPress/wporg-parent-2021/pull/53
