### ISSUE TITLE
Preset image heights for better rendering.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#43]
We should give images widths and heights on page load to prevent layout jank.

**Comment by adamwoodnz** [comment]
Could we base it on an aspect ratio? I imagine that would be quite easy aprt from the fact that some previews aren't consistent, eg. The National Puerto Rican Day Parade

![Screen Shot 2022-12-01 at 3 40 16 PM](https://user-images.githubusercontent.com/1017872/204953080-c2b63761-af2b-4421-b12c-1d4196f59e75.jpg)

Why is that one different?

I assume it is the previews we're referring to... ?

**Comment by StevenDufresne** [comment]
> Could we base it on an aspect ratio? I imagine that would be quite easy apart from the fact that some previews aren't consistent, eg. The National Puerto Rican Day Parade

We can assume that all the sites will have the same aspect ratio.

**Comment by StevenDufresne** [comment]
For clarity, we want to avoid the cumulative layout shift.

**GIF**:
![Screen Capture on 2022-12-01 at 12-57-40](https://user-images.githubusercontent.com/1657336/204962535-8ddfe8ca-b672-4538-b0c3-99a3a0feb375.gif)

**Comment by StevenDufresne** [comment]
Noting: I just enforced the aspect ratio in [6ca6458](https://github.com/WordPress/wporg-showcase-2022/commit/6ca64583f2b75d8b8548e34b2f7a9970f4f6cc5a)

**Comment by adamwoodnz** [comment]
Nice! Does that fix the issue or is there more work to do?

**Comment by adamwoodnz** [comment]
Appears to be fixed for me on the test site, and I see browser support is good. Only Safari 14 is lacking, but I'd consider this progressive enhancement.

**Comment by StevenDufresne** [comment]
> Appears to be fixed for me on the test site, and I see browser support is good. Only Safari 14 is lacking, but I'd consider this progressive enhancement.

The ratio is fixed but the images still don't have heights & widths on render causing layout shifts.

**Comment by adamwoodnz** [comment]
But I don't see a layout shift anymore...

![Kapture 2022-12-06 at 11 28 14](https://user-images.githubusercontent.com/1017872/205756643-50b7a5f6-92cc-4bce-a9b2-b243ee7c7b27.gif)

I think having the aspect ratio and width set should be enough?

```
.wp-block-wporg-site-screenshot img {
    aspect-ratio: 16/9;
    vertical-align: middle;
    width: 100%;
}
```

**Comment by StevenDufresne** [comment]
> But I don't see a layout shift anymore...

Ah, you're right, I must have run the tests on an out-of-date sandbox. I wasn't aware that aspect-ratio solved this problem. 🎸
