### ISSUE TITLE
Hide Submit a Site link in the navigation of the submission form

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-showcase-2022#80]
The Submit a Site page shouldn't link to itself from the navigation bar. I've updated [the design](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase-Pages?node-id=1%3A2193) to reflect that.

![image](https://user-images.githubusercontent.com/4933/205663429-6616a298-8c15-49c6-9814-cffef7313cc8.png)

**Comment by StevenDufresne** [comment]
I think this will be trickier than it seems. Can we push this to a future iteration?

**Comment by javierarce** [comment]
Yes, of course, I think this can wait.
