### ISSUE TITLE
Increase the font-size of the titles to 20px

### ISSUE THREAD

**Issue by javierarce** [WordPress/wporg-showcase-2022#81]
Let's increase the size of the titles under the thumbnails to 20px on the desktop so the hierarchy is noticeable. 

![image](https://user-images.githubusercontent.com/4933/205663945-1576a06c-e88b-407b-ae31-6859c2fb01fb.png)

The titles under the related sites in the single views can continue being 16px.

**Comment by StevenDufresne** [comment]
> Let's increase the size of the titles under the thumbnails to 20px **on the desktop** so the hierarchy is noticeable.

Does that mean it's `16px` on mobile? I would suggest we choose only one font size. I think we would want to avoid a complicated system of clamped/responsive text sizes especially if we want this to be managed by a non-dev team moving forward. 

I'll update it to `20px` seeing that's what it is in the Figma.

**Comment by StevenDufresne** [comment]
Implemented in [22c5424](https://github.com/WordPress/wporg-showcase-2022/commit/22c54240cc5499072d2a2a8f4b4b5fa18a8cff42)
