### ISSUE TITLE
Replace social image.

### ISSUE THREAD

**Issue by StevenDufresne** [WordPress/wporg-showcase-2022#83]
In PR #79, we introduced social media code along with a placeholder image. 

We should replace that placeholder with one provided by the design team.

**Comment by javierarce** [comment]
Here's the social image:

![image](https://user-images.githubusercontent.com/4933/206691596-bb234ca2-ece6-44b2-822d-bef3be5c35cd.png)

[Link to the asset in Figma](https://www.figma.com/file/nK6LcMOZMtRAQdIky3PNIA/Showcase-Pages?node-id=1951%3A25192&t=0jkqxE28XhkcT9wC-4)

**Comment by StevenDufresne** [comment]
Thanks. I exported it to a jpg because `4.1 MB was a bit too heavy. I think the difference is negligible (if noticeable at all) in the context in which it is used.

Implemented in https://github.com/WordPress/wporg-showcase-2022/commit/b8f80cda2c33436cf3058045dc090041c44f65ec.
